apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-mcp-sa
  namespace: postgres-mcp
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::__AWS_ACCOUNT_ID__:role/postgres-mcp-sa-role
